using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using DomainDoc = SignVault.Api.Domain.Document;
using DomainSig = SignVault.Api.Domain.Signature;

namespace SignVault.Api.Services;

/// <summary>Builds a one-page PDF certificate/receipt for a signed document.</summary>
public static class CertificatePdf
{
    private const string Ink = "#0f172a";
    private const string Muted = "#94a3b8";
    private const string Accent = "#1f7fc2";

    public static byte[] Build(DomainDoc doc, DomainSig sig) =>
        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(44);
                page.DefaultTextStyle(t => t.FontSize(11).FontColor(Ink).FontFamily("Lato"));

                page.Header().Row(row =>
                {
                    row.RelativeItem().Column(c =>
                    {
                        c.Item().Text("SignVault").FontSize(18).Bold().FontColor(Ink);
                        c.Item().Text("Certificate of Digital Signature").FontSize(11).FontColor(Muted);
                    });
                    row.ConstantItem(120).AlignRight().AlignMiddle()
                       .Text("VERIFIED").FontSize(13).Bold().FontColor("#15a06b");
                });

                page.Content().PaddingVertical(24).Column(col =>
                {
                    col.Spacing(2);
                    col.Item().PaddingBottom(8).Text(
                        "This certifies that the document below was cryptographically signed by the " +
                        "SignVault signing authority and has not been altered since.")
                        .FontColor("#475569");

                    col.Item().PaddingVertical(8).LineHorizontal(1).LineColor("#e7ecf2");

                    Field(col, "Document", doc.FileName);
                    Field(col, "Document ID", doc.Id.ToString());
                    Field(col, "SHA-256", doc.ContentHash);
                    Field(col, "Signed by", string.IsNullOrWhiteSpace(sig.SignerName) ? "—" : sig.SignerName);
                    Field(col, "Signed at (UTC)", sig.SignedAt.ToString("yyyy-MM-dd HH:mm:ss 'UTC'"));
                    Field(col, "Algorithm", sig.Algorithm);
                    Field(col, "Certificate thumbprint", sig.CertThumbprint);

                    col.Item().PaddingTop(8).LineHorizontal(1).LineColor("#e7ecf2");

                    col.Item().PaddingTop(12).Text(t =>
                    {
                        t.Span("How to verify  ").Bold();
                        t.Span("On the SignVault site, open the Verify page and either enter the Document ID " +
                               "above or upload the original file. A valid result confirms the signer and that " +
                               "the file is unchanged.").FontColor("#475569");
                    });
                });

                page.Footer().AlignCenter().Text(t =>
                {
                    t.Span("Generated by SignVault — digital signature platform").FontSize(9).FontColor(Muted);
                });
            });
        }).GeneratePdf();

    private static void Field(ColumnDescriptor col, string label, string value) =>
        col.Item().PaddingVertical(5).Row(row =>
        {
            row.ConstantItem(160).Text(label).FontSize(10).FontColor(Muted);
            row.RelativeItem().Text(value).SemiBold();
        });
}
